/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/workers/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Job */
        post: operations["claim_job_private_workers_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/workers/jobs/{job_id}/artifacts/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presign Artifact */
        post: operations["presign_artifact_private_workers_jobs__job_id__artifacts_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/workers/jobs/{job_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Job */
        post: operations["complete_job_private_workers_jobs__job_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/workers/jobs/{job_id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fail Job */
        post: operations["fail_job_private_workers_jobs__job_id__fail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/workers/jobs/{job_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat */
        post: operations["heartbeat_private_workers_jobs__job_id__heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private/workers/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Worker */
        post: operations["register_worker_private_workers_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/compatibility/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compatibility Query */
        post: operations["compatibility_query_v0_compatibility_queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Environments */
        get: operations["list_environments_v0_environments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evaluation */
        post: operations["create_evaluation_v0_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/evaluations/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_v0_evaluations__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/evaluations/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Evaluation */
        post: operations["cancel_evaluation_v0_evaluations__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/evaluations/{job_id}/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluation Rollouts */
        get: operations["list_evaluation_rollouts_v0_evaluations__job_id__rollouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policies */
        get: operations["list_policies_v0_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_v0_policies__policy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Robots */
        get: operations["list_robots_v0_robots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rollouts */
        get: operations["list_rollouts_v0_rollouts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/rollouts/{rollout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rollout */
        get: operations["get_rollout_v0_rollouts__rollout_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_v0_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionSpec */
        ActionSpec: {
            /** Dimensions */
            dimensions?: number | null;
            /** Expected Rate Hz */
            expected_rate_hz?: number | null;
            /** Frame */
            frame?: string | null;
            /** Horizon */
            horizon?: number | null;
            /** Normalization Id */
            normalization_id?: string | null;
            /** Schema */
            schema: string;
        };
        /** Artifact */
        Artifact: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "video" | "observation_trace" | "predicted_action_trace" | "executed_action_trace" | "log" | "config";
            /** Media Type */
            media_type: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Uri */
            uri: string;
        };
        /** ArtifactPresignRequest */
        ArtifactPresignRequest: {
            /** Filename */
            filename: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "video" | "observation_trace" | "predicted_action_trace" | "executed_action_trace" | "log" | "config";
            /** Media Type */
            media_type: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ArtifactUploadGrant */
        ArtifactUploadGrant: {
            artifact: components["schemas"]["Artifact"];
            /** Required Headers */
            required_headers: {
                [key: string]: string;
            };
            /** Upload Url */
            upload_url: string;
        };
        /** Availability */
        Availability: {
            /**
             * Code
             * @enum {string}
             */
            code: "open" | "closed" | "unavailable";
            /** License */
            license: string;
            /**
             * Weights
             * @enum {string}
             */
            weights: "open" | "gated" | "closed" | "unavailable";
        };
        /** CompatibilityQuery */
        CompatibilityQuery: {
            minimum_evidence?: components["schemas"]["EvidenceLevel"] | null;
            /** Policy Ids */
            policy_ids?: string[] | null;
            /** Robot Profile Id */
            robot_profile_id: string;
            /** Robot Revision */
            robot_revision: string;
            /** Task Profile Id */
            task_profile_id: string;
            /** Task Revision */
            task_revision: string;
        };
        /** CompatibilityRecord */
        CompatibilityRecord: {
            best_evidence?: components["schemas"]["Evidence"] | null;
            /** Explanation */
            explanation: string;
            /** Id */
            id: string;
            /** Missing Requirements */
            missing_requirements?: string[];
            /** Policy Id */
            policy_id: string;
            /** Policy Revision */
            policy_revision: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Robot Profile Id */
            robot_profile_id: string;
            /** Robot Revision */
            robot_revision: string;
            /** Ruleset Revision */
            ruleset_revision: string;
            /** Score */
            score: number;
            status: components["schemas"]["CompatibilityStatus"];
            supported_paths: components["schemas"]["SupportedPaths"];
            /** Task Profile Id */
            task_profile_id: string;
            /** Task Revision */
            task_revision: string;
        };
        /**
         * CompatibilityStatus
         * @enum {string}
         */
        CompatibilityStatus: "NATIVE_REAL_VERIFIED" | "BRIDGED_REAL_VERIFIED" | "SIM_VERIFIED" | "FINE_TUNE_REQUIRED" | "RESEARCH_ONLY" | "UNKNOWN" | "INCOMPATIBLE";
        /** ControlSurface */
        ControlSurface: {
            /** Dimensions */
            dimensions?: number | null;
            /** Frame */
            frame?: string | null;
            /** Rate Hz */
            rate_hz?: number | null;
            /** Schema */
            schema: string;
            /** Units */
            units?: string[];
        };
        /** EnvironmentListResponse */
        EnvironmentListResponse: {
            /** Items */
            items: components["schemas"]["EvaluationEnvironmentSpec"][];
            /** Total */
            total: number;
        };
        /** EvaluationEnvironmentSpec */
        EvaluationEnvironmentSpec: {
            /** Action Schema */
            action_schema: string;
            /** Benchmark */
            benchmark: string;
            /** Container Digest */
            container_digest: string;
            /** Container Image */
            container_image: string;
            /** Default Seeds */
            default_seeds: number[];
            /** Evaluator */
            evaluator: string;
            /** Id */
            id: string;
            /** License Requirements */
            license_requirements?: string[];
            /** Name */
            name: string;
            /** Observation Schema */
            observation_schema: string;
            /** Revision */
            revision: string;
            /** Robot Profile Id */
            robot_profile_id: string;
            /** Simulator */
            simulator: string;
            /** Suite */
            suite: string;
            /** Task Profile Id */
            task_profile_id: string;
        };
        /** EvaluationJob */
        EvaluationJob: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Failure Detail */
            failure_detail?: string | null;
            /** Failure Kind */
            failure_kind?: ("infrastructure" | "invalid_request" | "policy" | "canceled") | null;
            /** Id */
            id: string;
            /** Lease Expires At */
            lease_expires_at?: string | null;
            request: components["schemas"]["EvaluationJobCreate"];
            /**
             * Retry Safe
             * @default false
             */
            retry_safe: boolean;
            state: components["schemas"]["EvaluationState"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Worker Id */
            worker_id?: string | null;
        };
        /** EvaluationJobCreate */
        EvaluationJobCreate: {
            /** Environment Id */
            environment_id: string;
            /** Environment Revision */
            environment_revision: string;
            /** Policy Id */
            policy_id: string;
            /** Policy Revision */
            policy_revision: string;
            /** Seeds */
            seeds: number[];
            /** Task Profile Id */
            task_profile_id: string;
            /** Task Revision */
            task_revision: string;
        };
        /**
         * EvaluationState
         * @enum {string}
         */
        EvaluationState: "QUEUED" | "CLAIMED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELED";
        /** Evidence */
        Evidence: {
            /**
             * Checked At
             * Format: date
             */
            checked_at: string;
            /** Description */
            description: string;
            /**
             * Exact Robot Match
             * @default false
             */
            exact_robot_match: boolean;
            /**
             * Exact Runtime Match
             * @default false
             */
            exact_runtime_match: boolean;
            level: components["schemas"]["EvidenceLevel"];
            /**
             * Source
             * Format: uri
             */
            source: string;
        };
        /**
         * EvidenceLevel
         * @enum {string}
         */
        EvidenceLevel: "NATIVE_REAL_VERIFIED" | "BRIDGED_REAL_VERIFIED" | "SIM_VERIFIED" | "UPSTREAM_REPRODUCTION" | "RESEARCH_ONLY" | "UNKNOWN";
        /** ExecutablePolicySpec */
        ExecutablePolicySpec: {
            actions?: components["schemas"]["ActionSpec"] | null;
            availability: components["schemas"]["Availability"];
            /** Description */
            description: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Family */
            family: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            observations: components["schemas"]["ObservationRequirements"];
            /** Revision */
            revision: string;
            /** Robot Classes */
            robot_classes: string[];
            /**
             * Role
             * @default policy
             */
            role: string;
            runtime?: components["schemas"]["RuntimeSpec"] | null;
            source: components["schemas"]["SourceSpec"];
            /** Tags */
            tags?: string[];
            /** Task Families */
            task_families: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ObservationRequirements */
        ObservationRequirements: {
            /** Cameras */
            cameras?: string[];
            /**
             * Language Prompt
             * @default false
             */
            language_prompt: boolean;
            /** Sensor Types */
            sensor_types?: string[];
            /** State Schema */
            state_schema?: string | null;
        };
        /** PolicyListResponse */
        PolicyListResponse: {
            /** Items */
            items: components["schemas"]["ExecutablePolicySpec"][];
            /** Total */
            total: number;
        };
        /** RobotListResponse */
        RobotListResponse: {
            /** Items */
            items: components["schemas"]["RobotProfile"][];
            /** Total */
            total: number;
        };
        /** RobotProfile */
        RobotProfile: {
            /** Control Surfaces */
            control_surfaces: components["schemas"]["ControlSurface"][];
            /** Id */
            id: string;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Middleware */
            middleware: string;
            /** Model */
            model?: string | null;
            /** Name */
            name: string;
            /** Revision */
            revision: string;
            /** Robot Class */
            robot_class: string;
            /** Safety Capabilities */
            safety_capabilities?: {
                [key: string]: boolean;
            };
            /** Sensors */
            sensors: components["schemas"]["Sensor"][];
            /**
             * Simulated
             * @default false
             */
            simulated: boolean;
        };
        /** Rollout */
        Rollout: {
            /** Artifacts */
            artifacts?: components["schemas"]["Artifact"][];
            /** Duration Ms */
            duration_ms: number;
            /** Environment Id */
            environment_id: string;
            /** Environment Revision */
            environment_revision: string;
            /** Evaluation Job Id */
            evaluation_job_id?: string | null;
            /** Evidence Note */
            evidence_note?: string | null;
            /** Id */
            id: string;
            /** Metrics */
            metrics: {
                [key: string]: number | boolean;
            };
            /**
             * Mode
             * @enum {string}
             */
            mode: "sim" | "shadow" | "actuate";
            /** Policy Revision */
            policy_revision: string;
            /** Policy Spec Id */
            policy_spec_id: string;
            /** Robot Profile Id */
            robot_profile_id: string;
            /** Robot Revision */
            robot_revision: string;
            /** Runtime Identity */
            runtime_identity: {
                [key: string]: string;
            };
            /** Safety */
            safety?: {
                [key: string]: unknown;
            };
            /** Seed */
            seed: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Success */
            success: boolean;
            /** Task Profile Id */
            task_profile_id: string;
            /** Task Revision */
            task_revision: string;
        };
        /** RolloutListResponse */
        RolloutListResponse: {
            /** Items */
            items: components["schemas"]["Rollout"][];
            /** Total */
            total: number;
        };
        /** RuntimeSpec */
        RuntimeSpec: {
            /** Adapter */
            adapter: string;
            /** Config */
            config?: string | null;
            /** Engine Revision */
            engine_revision?: string | null;
            /** Framework */
            framework: string;
            /** Framework Revision */
            framework_revision: string;
        };
        /** Sensor */
        Sensor: {
            /** Dimensions */
            dimensions?: number | null;
            /** Id */
            id: string;
            /** Rate Hz */
            rate_hz?: number | null;
            /** Resolution */
            resolution?: [
                number,
                number
            ] | null;
            /** Semantic Name */
            semantic_name?: string | null;
            /** Type */
            type: string;
        };
        /** SourceSpec */
        SourceSpec: {
            /** Checkpoint */
            checkpoint?: string | null;
            /** Checkpoint Revision */
            checkpoint_revision?: string | null;
            /**
             * Repository
             * Format: uri
             */
            repository: string;
        };
        /** SupportedPaths */
        SupportedPaths: {
            /**
             * Actuate
             * @default false
             */
            actuate: boolean;
            /**
             * Shadow
             * @default false
             */
            shadow: boolean;
            /** Simulate */
            simulate: boolean;
        };
        /** TaskListResponse */
        TaskListResponse: {
            /** Items */
            items: components["schemas"]["TaskProfile"][];
            /** Total */
            total: number;
        };
        /** TaskProfile */
        TaskProfile: {
            /** Domain */
            domain: string;
            /** Environment */
            environment?: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /**
             * Language Conditioned
             * @default false
             */
            language_conditioned: boolean;
            /** Max Episode S */
            max_episode_s?: number | null;
            /** Name */
            name: string;
            /** Requirements */
            requirements?: string[];
            /** Revision */
            revision: string;
            /** Task Family */
            task_family: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkerCapabilities */
        WorkerCapabilities: {
            /** Adapters */
            adapters: string[];
            /** Cuda */
            cuda: boolean;
            /** Environments */
            environments: string[];
            /** Gpu Name */
            gpu_name?: string | null;
            /** Vram Gb */
            vram_gb?: number | null;
            /** Worker Id */
            worker_id: string;
        };
        /** WorkerCompletion */
        WorkerCompletion: {
            /** Rollouts */
            rollouts: components["schemas"]["Rollout"][];
        };
        /** WorkerFailure */
        WorkerFailure: {
            /** Detail */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "infrastructure" | "invalid_request" | "policy";
            /**
             * Retry Safe
             * @default false
             */
            retry_safe: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    claim_job_private_workers_claim_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerCapabilities"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationJob"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_artifact_private_workers_jobs__job_id__artifacts_presign_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactPresignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactUploadGrant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_job_private_workers_jobs__job_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerCompletion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fail_job_private_workers_jobs__job_id__fail_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerFailure"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heartbeat_private_workers_jobs__job_id__heartbeat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_worker_private_workers_register_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerCapabilities"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerCapabilities"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compatibility_query_v0_compatibility_queries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompatibilityQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_environments_v0_environments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentListResponse"];
                };
            };
        };
    };
    create_evaluation_v0_evaluations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_v0_evaluations__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_evaluation_v0_evaluations__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluation_rollouts_v0_evaluations__job_id__rollouts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_v0_policies_get: {
        parameters: {
            query?: {
                q?: string | null;
                robot_class?: string | null;
                task_family?: string | null;
                executable?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_v0_policies__policy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutablePolicySpec"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_robots_v0_robots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotListResponse"];
                };
            };
        };
    };
    list_rollouts_v0_rollouts_get: {
        parameters: {
            query?: {
                policy_id?: string | null;
                environment_id?: string | null;
                task_profile_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolloutListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rollout_v0_rollouts__rollout_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rollout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rollout"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_v0_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
        };
    };
}
