"""initial control plane schema

Revision ID: c9816ab7cca2
Revises:
Create Date: 2026-08-20 10:30:34.715508
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c9816ab7cca2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compatibility_records",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.String(length=120), nullable=False),
        sa.Column("cache_key", sa.String(length=600), nullable=False),
        sa.Column("record", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("cache_key"),
        sa.UniqueConstraint("record_id"),
    )
    op.create_table(
        "evaluation_environments",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("environment_id", sa.String(length=120), nullable=False),
        sa.Column("revision", sa.String(length=180), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("environment_id", "revision"),
    )
    op.create_index(
        op.f("ix_evaluation_environments_environment_id"), "evaluation_environments", ["environment_id"], unique=False
    )
    op.create_table(
        "evaluation_jobs",
        sa.Column("job_id", sa.String(length=120), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("worker_id", sa.String(length=120), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_kind", sa.String(length=80), nullable=True),
        sa.Column("failure_detail", sa.Text(), nullable=True),
        sa.Column("retry_safe", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(op.f("ix_evaluation_jobs_state"), "evaluation_jobs", ["state"], unique=False)
    op.create_table(
        "policies",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.String(length=120), nullable=False),
        sa.Column("revision", sa.String(length=180), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("family", sa.String(length=120), nullable=False),
        sa.Column("robot_classes", sa.JSON(), nullable=False),
        sa.Column("task_families", sa.JSON(), nullable=False),
        sa.Column("runtime_adapter", sa.String(length=120), nullable=True),
        sa.Column("evidence_level", sa.String(length=80), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("policy_id", "revision"),
    )
    op.create_index(op.f("ix_policies_evidence_level"), "policies", ["evidence_level"], unique=False)
    op.create_index(op.f("ix_policies_family"), "policies", ["family"], unique=False)
    op.create_index(op.f("ix_policies_name"), "policies", ["name"], unique=False)
    op.create_index(op.f("ix_policies_policy_id"), "policies", ["policy_id"], unique=False)
    op.create_index(op.f("ix_policies_runtime_adapter"), "policies", ["runtime_adapter"], unique=False)
    op.create_table(
        "robot_profiles",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.String(length=120), nullable=False),
        sa.Column("revision", sa.String(length=120), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("profile_id", "revision"),
    )
    op.create_index(op.f("ix_robot_profiles_profile_id"), "robot_profiles", ["profile_id"], unique=False)
    op.create_table(
        "rollouts",
        sa.Column("rollout_id", sa.String(length=120), nullable=False),
        sa.Column("evaluation_job_id", sa.String(length=120), nullable=True),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("rollout_id"),
    )
    op.create_index(op.f("ix_rollouts_created_at"), "rollouts", ["created_at"], unique=False)
    op.create_index(op.f("ix_rollouts_evaluation_job_id"), "rollouts", ["evaluation_job_id"], unique=False)
    op.create_table(
        "task_profiles",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.String(length=120), nullable=False),
        sa.Column("revision", sa.String(length=120), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("profile_id", "revision"),
    )
    op.create_index(op.f("ix_task_profiles_profile_id"), "task_profiles", ["profile_id"], unique=False)
    op.create_table(
        "workers",
        sa.Column("worker_id", sa.String(length=120), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workers")
    op.drop_index(op.f("ix_task_profiles_profile_id"), table_name="task_profiles")
    op.drop_table("task_profiles")
    op.drop_index(op.f("ix_rollouts_evaluation_job_id"), table_name="rollouts")
    op.drop_index(op.f("ix_rollouts_created_at"), table_name="rollouts")
    op.drop_table("rollouts")
    op.drop_index(op.f("ix_robot_profiles_profile_id"), table_name="robot_profiles")
    op.drop_table("robot_profiles")
    op.drop_index(op.f("ix_policies_runtime_adapter"), table_name="policies")
    op.drop_index(op.f("ix_policies_policy_id"), table_name="policies")
    op.drop_index(op.f("ix_policies_name"), table_name="policies")
    op.drop_index(op.f("ix_policies_family"), table_name="policies")
    op.drop_index(op.f("ix_policies_evidence_level"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_evaluation_jobs_state"), table_name="evaluation_jobs")
    op.drop_table("evaluation_jobs")
    op.drop_index(op.f("ix_evaluation_environments_environment_id"), table_name="evaluation_environments")
    op.drop_table("evaluation_environments")
    op.drop_table("compatibility_records")
    # ### end Alembic commands ###
